export const defaultData = [
  {
    id: "_1",
    performer: "Pasha",
    title: "first",
    fullText: "Some text",
    flag: "todoTasks",
  },
  {
    id: "_2",
    performer: "Pasha",
    title: "second",
    fullText: "Some text",
    flag: "todoTasks",
  },
  {
    id: "_3",
    performer: "Sasha",
    title: "Sasha's",
    fullText: "Some text",
    flag: "todoTasks",
  },
  {
    id: "_4",
    performer: "Pasha",
    title: "first",
    fullText: "Some text",
    description: "Pasha's first started post.",
    flag: "startedTasks",
  },
  {
    id: "_5",
    performer: "Pasha",
    title: "second",
    fullText: "Some text",
    flag: "startedTasks",
  },
  {
    id: "_6",
    performer: "Sasha",
    title: "Sasha's",
    fullText: "Some text",
    flag: "startedTasks",
  },
];
