export const CREATE_NEW_TASK = "CREATE_NEW_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const MOVER = "MOVER";

export const SET_AUTH = "SET_AUTH";
export const START_LOGIN = "START_LOGIN";
export const OBTAIN_LOGIN_DATA = "OBTAIN_LOGIN_DATA";
export const OBTAIN_LOGIN_ERROR = "OBTAIN_LOGIN_ERROR";
export const OBTAIN_FINISH_DATA = "OBTAIN_FINISH_DATA";
export const START_FINISH_REGISTER = "START_FINISH_REGISTER";
