export const CREATE_NEW_TODO = "CREATE_NEW_TODO";
export const DELETE_NEW_TODO = "DELETE_NEW_TODO";
export const DELETE_INWORK_TODO = "DELETE_INWORK_TODO";

export const MOVE_TO_INWORK_TASKS = "MOVE_TO_INWORK_TASKS";
export const REMOVE_TO_NEW_TASKS = "REMOVE_TO_NEW_TASKS";
